#!/bin/sh
#
# neutron-zvm-agent  OpenStack z/VM plugin
#
# chkconfig:   - 98 02
# description: Support z/VM vswitch network
### END INIT INFO

. /etc/rc.d/init.d/functions

proj=neutron
plugin=zvm-agent
prog=$proj-$plugin
exec="/usr/bin/$prog"
config="/etc/$proj/plugins/zvm/neutron_zvm_plugin.ini"
plugin_config="/etc/$proj/plugins/ml2/ml2_conf.ini"
pidfile="/var/run/$proj/$prog.pid"
logfile="/var/log/$proj/$plugin.log"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    [ -f $plugin_config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user neutron --pidfile $pidfile "$exec --config-file /etc/$proj/$proj.conf --config-file $plugin_config --config-file $config --log-file $logfile &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
